# Generated by Django 4.1 on 2022-10-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculator',
        ),
    ]
